apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: distribute-restorepoint-pipeline
spec:
  
  params:
    - name: namespace
      description: the namespace to backup and distribute restorepoint
    - name: locationprofile-name-1
      description: name of the first location profile 
    - name: locationprofile-name-2
      description: name of the second location profile  
  
  workspaces:
    - name: config    
      description: The kubeconfig of the cluster
  
  tasks:
    - name: backup
      taskRef:
        name: backupaction
      workspaces:
      - name: kubeconfig-dir
        workspace: config
      params:
      - name: namespace
        value: $(params.namespace)

    - name: export1
      runAfter:
        - backup
      taskRef:
        name: exportaction
      workspaces:
      - name: kubeconfig-dir
        workspace: config
      params:
      - name: restorepoint-name
        value: $(tasks.backup.results.restorepoint-name)
      - name: namespace
        value: $(params.namespace) 
      - name: locationprofile-name
        value: $(params.locationprofile-name-1) 
    
    - name: export2
      runAfter:
        - backup
      taskRef:
        name: exportaction
      workspaces:
      - name: kubeconfig-dir
        workspace: config
      params:
      - name: restorepoint-name
        value: $(tasks.backup.results.restorepoint-name)
      - name: namespace
        value: $(params.namespace) 
      - name: locationprofile-name
        value: $(params.locationprofile-name-2) 
        